apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s
      queryTimeout: 60s
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger
          datasourceType: jaeger 